version: 2

models:
  - name: stg_orders
    description: List of orders
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - placed
                - return_pending
      - name: customer_id
        description: Reference to snap_customers table
        tests:
          - not_null
          - unique: # fake test
              meta:
                tags: ["critical"]
                description: "Uniqueness violated for column stg_orders.customer_id"
          - relationships:
              to: ref('snap_customers')
              field: id
      - name: order_date
        description: Order date
      - name: order_timestamp
        description: Order timestamp

  - name: stg_payments
    columns:
      - name: payment_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        description: '{{ doc("payment_status") }}'
        tests:
          - accepted_values:
              values: 
                - success
                - fail
      - name: order_id
        description: Reference to stg_orders table
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: amount
        description: Payment amount in cents
      - name: payment_method
        description: '{{ doc("payment_method") }}'
        tests:
          - accepted_values:
              values:
                - gift_card
                - coupon
                - credit_card
                - bank_transfer
      - name: created
        description: Payment date
        tests:
          - not_null
          - unique: # fake test
              meta:
                tags: ["critical"]
                description: "Uniqueness violated for column stg_payments.created"
      - name: created_timestamp
        description: Payment timestamp

  - name: dim_customers
    columns:
      - name: customer_id
        description: Primary key. Derived from dbt_scd_id (snap_customers). dbt_scd_id is a unique key generated by dbt for each snapshotted record. It is a MD5 hash of primary_key and updated_at.
        tests:
          - unique
          - not_null
      - name: updated_at
        description: Timestamp - designates the time when the record was updated. Derived from dbt_updated_at (snap_customers).
      - name: valid_from
        description: Valid from
      - name: valid_to
        description: Valid to
      - name: customer_source_id
        description: ID of the customer in the source table (jaffle_shop_customers)
        tests:
          - not_null
      - name: first_name
        description: First name
        tests:
          - not_null
      - name: last_name
        description: Last name
        tests:
          - not_null
      - name: email
        description: Email
        tests:
          - not_null


        