version: 2

models:
  - name: stg_customers
    description: Customer information table
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: List of orders
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - placed
                - return_pending
      - name: customer_id
        description: Reference to stg_customers table
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: Order date

  - name: stg_payments
    columns:
      - name: payment_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        description: Payment status
        tests:
          - accepted_values:
              values: 
                - success
                - fail
      - name: order_id
        description: Reference to stg_orders table
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id