
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_databricks_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_databricks_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Project variables
vars:
  # The `valid_to_timestamp` variable will be accessible in all resources
  valid_to_timestamp: '2500-01-01T00:00:00.000+0000'
  days_offset_incr_load: -3

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_databricks_demo:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      +materialized: table
      +schema: bronze
      +meta:
        owner: "@albena.koteva-pavlidis"
        subscribers: ["@albena.koteva-pavlidis"]
        description: "dbt Databricks demo"
        tags: ["bronze"]
        channel: data-accelerator-dbt-demo
        alert_suppression_interval: 24 # a snooze period (in hours) for alerts on the same issue 
        #slack_group_alerts_by: alert # a single Slack notification will be generated containing all issues associated with a certain table
        alert_fields: ["description", "owners", "tags", "subscribers"]
    silver:
      +materialized: view
      +schema: silver
      +meta:
        owner: "@albena.koteva-pavlidis"
        subscribers: ["@albena.koteva-pavlidis"]
        description: "dbt Databricks demo"
        tags: ["silver"]
        channel: data-accelerator-dbt-demo
        alert_suppression_interval: 24 # a snooze period (in hours) for alerts on the same issue 
        #slack_group_alerts_by: table # a single Slack notification will be generated containing all issues associated with a certain table
        alert_fields: ["description", "owners", "tags", "subscribers"]
    gold:
      +materialized: table
      +schema: gold
      +meta:
        owner: "@albena.koteva-pavlidis"
        subscribers: ["@albena.koteva-pavlidis"]
        description: "dbt Databricks demo"
        tags: ["gold"]
        channel: data-accelerator-dbt-demo
        alert_suppression_interval: 24 # a snooze period (in hours) for alerts on the same issue 
        #slack_group_alerts_by: table # a single Slack notification will be generated containing all issues associated with a certain table
        alert_fields: ["description", "owners", "tags", "subscribers"]
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"